### ISSUE TITLE
Refactor Dockerfile so we don't have to build cross-compiler every time, and to control deps

### ISSUE THREAD

**Issue by anthony-cros** [doublethinkco/webthree-umbrella-cross#18]

**Comment by bobsummerwill** [comment]
What exactly was the proposed split here again?    Dockerfile for crosstool-ng on its own, then using the generated binaries in a second container for the actual cross-building?    What is the third piece again?   @anthony-cros

**Comment by anthony-cros** [comment]
i was going to suggest:

1. ubuntu augmented with dependencies (build-essentials, bzip2, ...)
2. crosstool-ng
3. eth

**Comment by anthony-cros** [comment]
just because they are all quite independent

though we could add a 2.5: adding dependencies for eth only (and keep 1. for ct-ng's dependencies only)

**Comment by bobsummerwill** [comment]
Right, and (3) and (2) would both be built on top of (1), right?    With "based on" or whatever the syntax is.

And we would do that model instead of (1) -> (2) -> (3), because we end up with a bunch of dependencies when we are USING the cross-compiler which we don't actually need or want for the eth build itself.

So we would switch to that composition model, and then just store the built binaries for the xcompiler, and copy those into the (3) environment.

**Comment by anthony-cros** [comment]
Yes exactly, the "FROM" syntax

good point for the ct-ng dependencies, actually they do pollute the environment unnecessarily for eth

**Comment by bobsummerwill** [comment]
OK - made a start on this.
See https://github.com/doublethinkco/webthree-umbrella-cross/blob/master/Dockerfile-xcompiler

**Comment by bobsummerwill** [comment]
DONE!
