### ISSUE TITLE
cross-build to become a sub-module itself

### ISSUE THREAD

**Issue by anthony-cros** [doublethinkco/webthree-umbrella-cross#19]

**Comment by bobsummerwill** [comment]
Please could you explain this one more, @anthony-cros?   Thanks!

**Comment by anthony-cros** [comment]
I was thinking that we could let "webthree-umbrella" be really just a wrapper, and that we could take "cross-build" out of it and link to it as a sub-module the same we are doing with the other sub-component ("libweb3core", "libethereum", ...).

**Comment by bobsummerwill** [comment]
I don't know that there is much benefit in that.    Not a priority for me.     I'm going to have to stew on what the best way of upstreaming all of this stuff is going to be, but I don't see much benefit in a special repo here, because the cross-build (like the native build) is so intimately tied in with the umbrella.

**Comment by anthony-cros** [comment]
yes, I didn't consider that actually, probably not a good idea!
