### ISSUE TITLE
Dockerfile: apply light client PR to go-ethereum-cross

### ISSUE THREAD

**Issue by anthony-cros** [doublethinkco/webthree-umbrella-cross#24]

**Comment by bobsummerwill** [comment]
I think this is high priority (after creation of the geth cross repo!) because it lets me build Light Client executables to mess around with while they are still working on the feature set.    I'm going to need this to be to get on the main network.    Doesn't matter if it's really unstable and churny.   Need it :-)

**Comment by bobsummerwill** [comment]
Replaced by https://github.com/doublethinkco/go-ethereum-cross/issues/7.
