### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by martinbrook** [doublethinkco/webthree-umbrella-cross#31]
HI

Thanks for fixing the submodules my build gets a lot further now.

However I run into this error:- 

cross-compiling: libmicrohttpd

CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/xcompiler/eth/151124090533/wd/libmicrohttpd/missing aclocal-1.15 -I m4
 cd . && /bin/bash /home/xcompiler/eth/151124090533/wd/libmicrohttpd/missing automake-1.15 --gnu
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/xcompiler/eth/151124090533/wd/libmicrohttpd/missing autoconf
configure.ac:46: error: possibly undefined macro: AC_MSG_CHECKING
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:63: error: possibly undefined macro: AC_MSG_RESULT
configure.ac:77: error: possibly undefined macro: AS_IF
configure.ac:110: error: possibly undefined macro: AC_LINK_IFELSE
configure.ac:111: error: possibly undefined macro: AC_LANG_PROGRAM
configure.ac:183: error: possibly undefined macro: AC_CHECK_HEADERS
configure.ac:207: error: possibly undefined macro: AC_MSG_WARN
configure.ac:592: error: possibly undefined macro: AC_CHECK_LIB
make: *** [configure] Error 1
INFO[0926] The command [/bin/sh -c ./main.sh ~/x-tools/arm-unknown-linux-gnueabi] returned a non-zero code: 2 

vgrade

**Comment by bobsummerwill** [comment]
Hi @martinbrook!   Welcome :-)
So @anthony-cros and @phonikg are both in Toronto.  It's still 8am here in Vancouver but I can investigate soon!

Let's talk at http://gitter.im/ethereum/porting (and on issues here!)

**Comment by phonikg** [comment]
FYI - This is the exact issue I had last night: https://gist.github.com/phonikg/2c4785c09f8357bf87b3

When I ran `automake --version` it said I had version `1.14`

Setup: 
Host Environment #1 - Laptop running Ubuntu 15.04
Host Environment #2 - Azure VM running Ubuntu 14.04LTS

**Comment by bobsummerwill** [comment]
From http://gitter.im/ethereum/porting ...

martinbrook 10:20
@phonikg touch configure.ac aclocal.m4 configure Makefile.am Makefile.in before configuring libmicrohttpd works ref SIPp/sipp#61

bobsummerwill 10:23
Good catch! The thing I'm still missing, though, is why host OS should matter when we're all inside docker containers anyway? That environment isolation is the whole point!
Unless you are running some steps from the dockerfile on your host OS, @martinbrook?
OK - So I can replicate this issue too now!
That is inside the Azure VM where the host is Ubuntu 15.04 rather than CoreOS.
I get:
cross-compiling: libmicrohttpd
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/xcompiler/eth/151124180001/wd/libmicrohttpd/missing aclocal-1.15 -I m4
/home/xcompiler/eth/151124180001/wd/libmicrohttpd/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
You should only need it if you modified 'acinclude.m4' or
'configure.ac' or m4 files included by 'configure.ac'.
The 'aclocal' program is part of the GNU Automake package:
http://www.gnu.org/software/automake
It also requires GNU Autoconf, GNU m4 and Perl in order to run:
http://www.gnu.org/software/autoconf
http://www.gnu.org/software/m4/
http://www.perl.org/
make: * [aclocal.m4] Error 127

martinbrook 10:29
@bobsummerwill if you check libmicrohttpd sources it looks like they include the tree after being configured (with 1.15) and it needs to regenerate things using the dockerhost tool versions. changing the timestamp forces this
15.04 still uses 1.14
https://github.com/doublethinkco/webthree-umbrella/pulls

bobsummerwill 10:34
Thanks for the fix, @martinbrook! Merged.
And I'll re-run my failing case on a clean run too.
I will have to read up about dockerhost. That dependency on external host tools is UGLY!

**Comment by bobsummerwill** [comment]
Likely fixed.    Just verifying with a clean run on Docker-on-Ubuntu in Azure.

**Comment by bobsummerwill** [comment]
I'm going to assume this is fixed.   Thanks, @martinbrook
